# Generated by Django 6.0.4 on 2026-04-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_payment_method_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price_per_box',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='strips_per_box',
            field=models.IntegerField(default=10),
        ),
    ]
