# Generated by Django 6.0.4 on 2026-04-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medicine_price_per_box_medicine_strips_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
