# Generated by Django 6.0.4 on 2026-04-30 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medicine_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
