# Generated by Django 6.0.4 on 2026-05-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_medicine_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='discount_percentage',
            new_name='box_discount_percent',
        ),
        migrations.AddField(
            model_name='medicine',
            name='strip_discount_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
