# Generated by Django 6.0.4 on 2026-05-12 22:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_phone_number_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
